imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true


# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
#    encryption:      "%mailer_encryption%"
    port:      "%mailer_port%"
#    auth_mode: "%mailer_auth_mode%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
            address: "etienne.cotin@gmail.com"
            sender_name: "etienne cotin"

    registration:
            form:
                type: AppBundle\Form\RegistrationType
                # if you are using Symfony < 2.8 you should use the type name instead
                # type: app_user_registration

# To solve the problem
    from_email:
        address: "etienne.cotin@gmail.com"
        sender_name: "etienne cotin"

easy_admin:
    site_name: 'Card lab'
    design:
            # 'dark' is the default value
            color_scheme: 'light'
            menu:
              - { label: 'Retour au site', route: 'homepage', icon: '' }
              - { label: 'Table' }
              - User
              - Partie
              - Carte
              - Categorie
              - Tournois
    entities:
        User:
                    class: AppBundle\Entity\User

                    form:
                          title : "Ajouter un utilisateur"
                          fields:
                              - { property: 'username', }
                              - { property: 'usernameCanonical', }
                              - { property: 'userNom', }
                              - { property: 'userPrenom', }
                              - { property: 'email', }
                              - { property: 'emailCanonical', }
                              - { property: 'enabled', }
                              - { property: 'salt', }
                              - { property: 'password', }
#                              - { property: 'plainPassword', }
                              - { property: 'lastLogin', }
                              - { property: 'confirmationToken', }
                              - { property: 'passwordRequestedAt', }
#                              - { property: 'groups', }
                              - { property: 'roles', }

#                              - { property: 'parties', label: 'test'}


        Partie:
                              class: AppBundle\Entity\Partie
                              list:
                                              actions:
                                                  - { name: 'show', icon: 'search', label: 'Voir' }
                                                  - { name: 'edit', icon: 'pencil', label: 'Modifier' }
                                                  - { name: 'delete', icon: 'times', label: 'Supprimer' }
                                              title: "Parties"
        Carte:
                    class: AppBundle\Entity\Carte

                    form:
                        title : "Créer une carte"
                        fields:
                            - { property: 'carteValeur', type: 'number' }
                            - { property: 'carteExtra' }
                            - { property: 'carteNom', type: 'text' }
                            - { property: 'carteImage', type: 'hidden'}
                            - { property: 'file', type: 'file', label: 'Image' }
                            - { property: 'carteCategorie' }
#                    edit:
#                                    fields:
#                                        - { property: 'carteImage', type: 'file' }

        Categorie:
                      class: AppBundle\Entity\Categorie

        Tournois:
                      class: AppBundle\Entity\Tournois
